<?php
/**
 * @package yii2-ews
 * @author Simon Karlen <simi.albi@gmail.com>
 */

namespace simialbi\yii2\ews;

use jamesiarmes\PhpEws\Request\BaseRequestType;
use Yii;
use yii\base\Component;
use yii\base\InvalidConfigException;
use yii\caching\CacheInterface;
use yii\caching\Dependency;

/**
 * Class Service
 * @package simialbi\yii2\ews
 *
 * @property-read Client $client
 */
class Connection extends Component
{
    /**
     * @var string The url to the exchange server you wish to connect to, without the protocol. Example:
     * mail.example.com.
     */
    public string $server;
    /**
     * @var string The explicit location to use. This property will override autogenerated location by [[$server]]
     * property if set.
     */
    public string $location;
    /**
     * @var string The user to connect to the server with. This is usually the local portion of the users email address.
     * Example: "user" if the email address is "user@example.com"
     */
    public string $username;
    /**
     * @var string The user's plain-text password.
     */
    public string $password;
    /**
     * @var bool whether to enable logging of database queries. Defaults to true.
     * You may want to disable this option in a production environment to gain performance
     * if you do not need the information being logged.
     * @see enableProfiling
     */
    public bool $enableLogging = true;
    /**
     * @var bool whether to enable profiling of opening database connection and database queries. Defaults to true.
     * You may want to disable this option in a production environment to gain performance
     * if you do not need the information being logged.
     * @see enableLogging
     */
    public bool $enableProfiling = true;
    /**
     * @var bool whether to enable query caching.
     * Note that in order to enable query caching, a valid cache component as specified
     * by [[queryCache]] must be enabled and [[enableQueryCache]] must be set true.
     * Also, only the results of the queries enclosed within [[cache()]] will be cached.
     * @see queryCache
     * @see cache()
     * @see noCache()
     */
    public bool $enableQueryCache = false;
    /**
     * @var int the default number of seconds that query results can remain valid in cache.
     * Defaults to 3600, meaning 3600 seconds, or one hour. Use 0 to indicate that the cached data will never expire.
     * The value of this property will be used when [[cache()]] is called without a cache duration.
     * @see enableQueryCache
     * @see cache()
     */
    public int $queryCacheDuration = 3600;
    /**
     * @var CacheInterface|string the cache object or the ID of the cache application component
     * that is used for query caching.
     * @see enableQueryCache
     */
    public string|CacheInterface $queryCache = 'cache';

    /**
     * @var array Sets additional cURL options that will be set in the SOAP client.
     * The keys are the one of the [[CURLOPT_*]] constants and the values the correspondig values:
     * ```php
     * [
     *     CURLOPT_CONNECTTIMEOUT => 10,
     *     CURLOPT_DNS_CACHE_TIMEOUT => 60
     * ]
     * ```
     */
    public array $curlOptions = [];

    /**
     * @var Client EWS Client instance.
     */
    private Client $_client;
    /**
     * @var array query cache parameters for the [[cache()]] calls
     */
    private array $_queryCacheInfo = [];

    /**
     * Get the [[Client]] instance.
     * @return Client
     * @throws InvalidConfigException
     */
    public function getClient(): Client
    {
        if (!isset($this->_client)) {
            $this->_client = new Client($this->server ?? null, $this->username, $this->password);
            if (!empty($this->location)) {
                $this->_client->setLocation($this->location);
            }
            $this->_client->setCurlOptions($this->curlOptions);
        }

        return $this->_client;
    }

    /**
     * Creates a command for execution.
     *
     * @param BaseRequestType|null $request
     * @param array $params
     * @return Command the DB command
     * @throws \yii\base\InvalidConfigException
     */
    public function createCommand(?BaseRequestType $request = null, array $params = []): Command
    {
        $config = [
            'class' => Command::class,
            'db' => $this,
            'request' => $request,
            'params' => $params
        ];

        /** @var Command $command */
        $command = Yii::createObject($config);

        return $command;
    }


    /**
     * Returns the query builder for the current DB connection.
     * @return QueryBuilder the query builder for the current DB connection.
     */
    public function getQueryBuilder(): QueryBuilder
    {
        return new QueryBuilder($this);
    }


    /**
     * Uses query cache for the queries performed with the callable.
     *
     * When query caching is enabled ([[enableQueryCache]] is true and [[queryCache]] refers to a valid cache),
     * queries performed within the callable will be cached and their results will be fetched from cache if available.
     * For example,
     *
     * ```php
     * // The customer will be fetched from cache if available.
     * // If not, the query will be made against DB and cached for use next time.
     * $customer = $db->cache(function (Connection $db) {
     *     return $db->createCommand([])->queryOne();
     * });
     * ```
     *
     * Note that query cache is only meaningful for queries that return results. For queries performed with
     * [[Command::execute()]], query cache will not be used.
     *
     * @param callable $callable a PHP callable that contains EWS operations which will make use of query cache.
     * The signature of the callable is `function (Connection $db)`.
     * @param int|null $duration the number of seconds that query results can remain valid in the cache. If this is
     * not set, the value of [[queryCacheDuration]] will be used instead.
     * Use 0 to indicate that the cached data will never expire.
     * @param \yii\caching\Dependency|null $dependency the cache dependency associated with the cached query results.
     * @return mixed the return result of the callable
     * @throws \Exception|\Throwable if there is any exception during query
     * @see enableQueryCache
     * @see queryCache
     * @see noCache()
     */
    public function cache(callable $callable, ?int $duration = null, ?\yii\caching\Dependency $dependency = null): mixed
    {
        $this->_queryCacheInfo[] = [$duration === null ? $this->queryCacheDuration : $duration, $dependency];
        try {
            $result = call_user_func($callable, $this);
            array_pop($this->_queryCacheInfo);
            return $result;
        } catch (\Exception | \Throwable $e) {
            array_pop($this->_queryCacheInfo);
            throw $e;
        }
    }

    /**
     * Disables query cache temporarily.
     *
     * Queries performed within the callable will not use query cache at all. For example,
     *
     * ```php
     * $db->cache(function (Connection $db) {
     *
     *     // ... queries that use query cache ...
     *
     *     return $db->noCache(function (Connection $db) {
     *         // this query will not use query cache
     *         return $db->createCommand([])->queryOne();
     *     });
     * });
     * ```
     *
     * @param callable $callable a PHP callable that contains EWS operations which should not use query cache.
     * The signature of the callable is `function (Connection $db)`.
     * @return mixed the return result of the callable
     * @throws \Exception|\Throwable if there is any exception during query
     * @see enableQueryCache
     * @see queryCache
     * @see cache()
     */
    public function noCache(callable $callable): mixed
    {
        $this->_queryCacheInfo[] = false;
        try {
            $result = call_user_func($callable, $this);
            array_pop($this->_queryCacheInfo);
            return $result;
        } catch (\Exception | \Throwable $e) {
            array_pop($this->_queryCacheInfo);
            throw $e;
        }
    }

    /**
     * Returns the current query cache information.
     * This method is used internally by [[Command]].
     * @param int|null $duration the preferred caching duration. If null, it will be ignored.
     * @param Dependency|null $dependency the preferred caching dependency. If null, it will be ignored.
     * @return array|null the current query cache information, or null if query cache is not enabled.
     * @throws InvalidConfigException
     * @internal
     */
    public function getQueryCacheInfo(?int $duration = null, ?\yii\caching\Dependency $dependency = null): ?array
    {
        if (!$this->enableQueryCache) {
            return null;
        }

        $info = end($this->_queryCacheInfo);
        if (is_array($info)) {
            if ($duration === null) {
                $duration = $info[0];
            }
            if ($dependency === null) {
                $dependency = $info[1];
            }
        }

        if ($duration >= 0) {
            if (is_string($this->queryCache) && Yii::$app) {
                $cache = Yii::$app->get($this->queryCache, false);
            } else {
                $cache = $this->queryCache;
            }
            if ($cache instanceof CacheInterface) {
                return [$cache, $duration, $dependency];
            }
        }

        return null;
    }
}
